### ISSUE TITLE
Find Document Lists [ITI-66] (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-fhir#180]
ch.fhir.ig.ch-epr-fhir#4.0.0-ci-build /iti-66.html

Can we remove this transaction? I don't see a use case for it in the Swiss Context (this corresponds to the SubmissionSet). 

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
Telco vom 8.5: remove transcation no use case

**Comment by staffoleo** [comment]
Hi Oliver,
We're actually planning to implement this. We'll need it to query all the documentReferences related to the same SubmissionSet.
The main use case will be to have in the same submissionSet a documentRefernece with the PDF and another documentReference with the fhir+json reperesentation.
Would there be other ways to achive the same thing?

**Comment by oliveregger** [comment]
@staffoleo thanks for the usecase, i was not aware that the structured data and represented data are stored separately. 

For the swiss exchange formats, the representation is either embedded (MedicationCard) or required to be done through a stylesheet (Vaccination). Do you have any other use cases?

>Would there be other ways to achive the same thing?

I would set [DocumentReference.relatesTo](https://hl7.org/fhir/R4/documentreference.html) code to transforms and query the related documents with relationship parameter and the code to `transforms`. there is a small problem, because MHD does not include this parameter int the list. 

however if that would be a solution I will propose a change to the [MHD Find Document References Request Message]( https://profiles.ihe.net/ITI/MHD/ITI-67.html#236741-find-document-references-request-message)

**Comment by oliveregger** [comment]
@staffoleo any update on this if you still need [ITI-66]?

**Comment by staffoleo** [comment]
It's perfectly fine to us to use the "relatesTo" code.
No objection in removing the transaction.

**Comment by oliveregger** [comment]
telco from 4.7: remove the transcation from the guide and make a note in ch:mhd that the transcation does not need to be supported.
